#This is the Basics printing all integers from 0 to 150

for n in range(0, 151):
    print(n)

#this is Multiples of five

res = [i for i in range(0, 1001, 5)] 
print(*res) 

# Counting the Dojo Way, print integers 1-100, if divisible by 5 print "Coding" instead, if divisible by 10 print "Coding Dojo"

#Add odd integers from 0 t0 500,000, and print the final sum.



#Print positive numbers starting at 2018 counting down by fours. 

for i in range(2018, 0, -4):
    print(i)

#Flexible counter.